apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-fe
  labels:
    name: despliegue-fe
    app: tone-analyzer-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tone-analyzer-pod
      app: tone-analyzer-fe
  template:
    metadata:
      name: tone-analyzer-pod
      labels:
        name: tone-analyzer-pod
        app: tone-analyzer-fe
    spec:
      containers:
      - name: tone-analyzer-container
        image: 001219492244.dkr.ecr.us-east-1.amazonaws.com/tone-analyzer-fe:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.2"
        livenessProbe:
          httpGet:
            path: /health
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
        
