apiVersion: v1
kind: Service
metadata:
  name: servicio-fe
  labels:
    name: despliegue-fe
    app: tone-analyzer-fe
spec:
  type: NodePort
  selector: 
    app: tone-analyzer-fe
  ports:
    - protocol: TCP
      port: 3500
      nodePort: 30027

        
